language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=default/x86

android:
  components:
    - build-tools-22.0.1
    - android-22
    - sys-img-x86-android-22
    - extra-android-support

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi default/x86
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew library:connectedAndroidTest --info
